server.error.whitelabel.enabled: false
server.servlet.context-path: /api

# Logging
logging:
  level:
    com.thalasoft: debug
    org:
      hibernate:
        SQL: debug
      springframework: trace
